jQuery(document).ready(function(){
    var scripts = document.getElementsByTagName("script");
    var jsFolder = "";
    for (var i= 0; i< scripts.length; i++)
    {
        if( scripts[i].src && scripts[i].src.match(/initslider-1\.js/i))
            jsFolder = scripts[i].src.substr(0, scripts[i].src.lastIndexOf("/") + 1);
    }
    jQuery("#amazingslider-1").amazingslider({
        jsfolder:jsFolder,
        width:1000,
        height:200,
        loadimageondemand:false,
        isresponsive:true,
        autoplayvideo:false,
        pauseonmouseover:false,
        addmargin:false,
        randomplay:false,
        slideinterval:3000,
        enabletouchswipe:true,
        transitiononfirstslide:false,
        loop:0,
        autoplay:true,
        navplayvideoimage:"play-32-32-0.png",
        navpreviewheight:60,
        timerheight:2,
        shownumbering:false,
        skin:"Lightbox",
        textautohide:false,
        addgooglefonts:true,
        navshowplaypause:true,
        navshowplayvideo:false,
        navbuttonradius:0,
        navpreviewposition:"top",
        navmarginy:-32,
        showshadow:false,
        navfeaturedarrowimagewidth:16,
        navpreviewwidth:120,
        googlefonts:"Inder",
        textpositionmarginright:0,
        bordercolor:"#ffffff",
        navthumbnavigationarrowimagewidth:32,
        navthumbtitlehovercss:"text-decoration:underline;",
        arrowwidth:32,
        texteffecteasing:"easeOutCubic",
        texteffect:"slide",
        navspacing:8,
        navarrowimage:"navarrows-28-28-0.png",
        ribbonimage:"ribbon_topleft-0.png",
        navwidth:16,
        navheight:16,
        arrowimage:"arrows-32-32-3.png",
        timeropacity:0.6,
        navthumbnavigationarrowimage:"carouselarrows-32-32-0.png",
        navpreviewbordercolor:"#ffffff",
        ribbonposition:"topleft",
        navthumbdescriptioncss:"display:block;position:relative;padding:2px 4px;text-align:left;font:normal 12px Arial,Helvetica,sans-serif;color:#333;",
        arrowstyle:"always",
        navthumbtitleheight:20,
        textpositionmargintop:24,
        navswitchonmouseover:false,
        playvideoimage:"playvideo-64-64-0.png",
        arrowtop:50,
        textstyle:"none",
        playvideoimageheight:64,
        navfonthighlightcolor:"#666666",
        showbackgroundimage:false,
        navpreviewborder:4,
        navdirection:"horizontal",
        navbuttonshowbgimage:true,
        navbuttonbgimage:"navbuttonbgimage-28-28-0.png",
        navthumbnavigationarrowimageheight:32,
        textbgcss:"display:block; position:absolute; top:0px; left:0px; width:100%; height:100%; background-color:#fff; opacity:0.7; filter:alpha(opacity=70);",
        shadowcolor:"#aaaaaa",
        navborder:4,
        bottomshadowimagewidth:110,
        showtimer:false,
        navradius:0,
        navshowpreview:false,
        navpreviewarrowheight:8,
        navmarginx:-32,
        navfeaturedarrowimage:"featuredarrow-16-8-0.png",
        showribbon:false,
        navfeaturedarrowimageheight:8,
        navstyle:"bullets",
        textpositionmarginleft:0,
        descriptioncss:"display:block; position:relative; font:14px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#333;",
        navplaypauseimage:"navplaypause-28-28-0.png",
        backgroundimagetop:-10,
        timercolor:"#ffffff",
        numberingformat:"%NUM/%TOTAL ",
        navfontsize:12,
        navhighlightcolor:"#333333",
        navimage:"bullet-16-16-0.png",
        navbuttoncolor:"#999999",
        navshowarrow:true,
        navshowfeaturedarrow:false,
        titlecss:"display:block; position:relative; font: 16px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#000;",
        ribbonimagey:0,
        ribbonimagex:0,
        shadowsize:5,
        arrowhideonmouseleave:1000,
        navopacity:0.8,
        backgroundimagewidth:120,
        navcolor:"#999999",
        navthumbtitlewidth:120,
        playvideoimagewidth:64,
        arrowheight:32,
        arrowmargin:0,
        texteffectduration:1000,
        bottomshadowimage:"bottomshadow-110-95-1.png",
        border:0,
        timerposition:"bottom",
        navfontcolor:"#333333",
        navthumbnavigationstyle:"auto",
        borderradius:0,
        navbuttonhighlightcolor:"#333333",
        textpositionstatic:"bottom",
        navthumbstyle:"imageonly",
        textcss:"display:block; padding:8px 16px; text-align:left; ",
        navbordercolor:"#ffffff",
        navpreviewarrowimage:"previewarrow-16-8-0.png",
        showbottomshadow:false,
        textpositionmarginstatic:0,
        backgroundimage:"",
        navposition:"bottom",
        navpreviewarrowwidth:16,
        bottomshadowimagetop:95,
        textpositiondynamic:"bottomleft",
        navshowbuttons:false,
        navthumbtitlecss:"display:block;position:relative;padding:2px 4px;text-align:left;font:bold 14px Arial,Helvetica,sans-serif;color:#333;",
        textpositionmarginbottom:24,
        slide: {
            duration:1000,
            easing:"easeOutCubic",
            checked:true
        },
        slice: {
            duration:1500,
            easing:"easeOutCubic",
            checked:true,
            effects:"up,down,updown",
            slicecount:10
        },
        blinds: {
            duration:2000,
            easing:"easeOutCubic",
            checked:true,
            slicecount:3
        },
        transition:"slide,slice,blinds"
    });
});

jQuery(document).ready(function () {
    var scripts = document.getElementsByTagName("script");
    var jsFolder = "";
    for (var i = 0; i < scripts.length; i++) {
        if (scripts[i].src && scripts[i].src.match(/initslider-1\.js/i))
            jsFolder = scripts[i].src.substr(0, scripts[i].src.lastIndexOf("/") + 1);
    }
    jQuery("#amazingslider-2").amazingslider({
        jsfolder: jsFolder,
        width: 360,
        height: 260,
        skinsfoldername: "skins",
        loadimageondemand: false,
        isresponsive: false,
        autoplayvideo: false,
        pauseonmouseover: false,
        addmargin: true,
        randomplay: false,
        slideinterval: 5000,
        enabletouchswipe: true,
        transitiononfirstslide: false,
        loop: 0,
        autoplay: true,
        navplayvideoimage: "play-32-32-0.png",
        navpreviewheight: 60,
        timerheight: 2,
        shownumbering: false,
        skin: "Gallery",
        textautohide: false,
        addgooglefonts: false,
        navshowplaypause: true,
        navshowplayvideo: true,
        navshowplaypausestandalonemarginx: 8,
        navshowplaypausestandalonemarginy: 8,
        navbuttonradius: 0,
        navthumbnavigationarrowimageheight: 32,
        navpreviewarrowheight: 8,
        showshadow: false,
        navfeaturedarrowimagewidth: 16,
        navpreviewwidth: 120,
        googlefonts: "Inder",
        textpositionmarginright: 24,
        bordercolor: "#ffffff",
        navthumbnavigationarrowimagewidth: 32,
        navthumbtitlehovercss: "text-decoration:underline;",
        arrowwidth: 32,
        texteffecteasing: "easeOutCubic",
        texteffect: "slide",
        navspacing: 8,
        navarrowimage: "navarrows-28-28-0.png",
        ribbonimage: "ribbon_topleft-0.png",
        navwidth: 48,
        showribbon: false,
        arrowtop: 50,
        timeropacity: 0.6,
        navthumbnavigationarrowimage: "carouselarrows-32-32-0.png",
        navshowplaypausestandalone: false,
        navpreviewbordercolor: "#ffffff",
        ribbonposition: "topleft",
        navthumbdescriptioncss: "display:block;position:relative;padding:2px 4px;text-align:left;font:normal 12px Arial,Helvetica,sans-serif;color:#333;",
        navborder: 1,
        navthumbtitleheight: 20,
        textpositionmargintop: 24,
        navswitchonmouseover: true,
        playvideoimage: "playvideo-64-64-0.png",
        arrowimage: "arrows-32-32-0.png",
        textstyle: "none",
        playvideoimageheight: 64,
        navfonthighlightcolor: "#666666",
        showbackgroundimage: false,
        navpreviewborder: 4,
        navopacity: 0.8,
        shadowcolor: "#aaaaaa",
        navbuttonshowbgimage: true,
        navbuttonbgimage: "navbuttonbgimage-28-28-0.png",
        textbgcss: "display:block; position:absolute; top:0px; left:0px; width:100%; height:100%; background-color:#fff; -webkit-border-radius: 2px; -moz-border-radius: 2px; border-radius: 2px; opacity:0.7; filter:alpha(opacity=70);",
        playvideoimagewidth: 64,
        bottomshadowimagewidth: 110,
        showtimer: false,
        navradius: 0,
        navshowpreview: false,
        navmarginy: 5,
        navmarginx: 16,
        navfeaturedarrowimage: "featuredarrow-16-8-0.png",
        navfeaturedarrowimageheight: 8,
        navstyle: "thumbnails",
        textpositionmarginleft: 24,
        descriptioncss: "display:block; position:relative; font:14px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#333;",
        navplaypauseimage: "navplaypause-28-28-0.png",
        backgroundimagetop: -10,
        arrowstyle: "mouseover",
        timercolor: "#ffffff",
        numberingformat: "%NUM/%TOTAL ",
        navfontsize: 12,
        navhighlightcolor: "#333333",
        navimage: "bullet-24-24-5.png",
        navheight: 48,
        navshowplaypausestandaloneautohide: false,
        navbuttoncolor: "#999999",
        navshowarrow: true,
        navshowfeaturedarrow: true,
        titlecss: "display:block; position:relative; font: 16px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#000;",
        ribbonimagey: 0,
        ribbonimagex: 0,
        navshowplaypausestandaloneposition: "bottomright",
        shadowsize: 5,
        arrowhideonmouseleave: 1000,
        navshowplaypausestandalonewidth: 28,
        navshowplaypausestandaloneheight: 28,
        backgroundimagewidth: 120,
        navcolor: "#999999",
        navthumbtitlewidth: 120,
        navpreviewposition: "top",
        arrowheight: 32,
        arrowmargin: 8,
        texteffectduration: 1000,
        bottomshadowimage: "bottomshadow-110-95-4.png",
        border: 1,
        timerposition: "bottom",
        navfontcolor: "#333333",
        navthumbnavigationstyle: "arrow",
        borderradius: 0,
        navbuttonhighlightcolor: "#333333",
        textpositionstatic: "bottom",
        navthumbstyle: "imageonly",
        textcss: "display:block; padding:8px 16px; text-align:left; ",
        navbordercolor: "#333845",
        navpreviewarrowimage: "previewarrow-16-8-0.png",
        showbottomshadow: false,
        navdirection: "horizontal",
        textpositionmarginstatic: 0,
        backgroundimage: "",
        navposition: "bottom",
        navpreviewarrowwidth: 16,
        bottomshadowimagetop: 95,
        textpositiondynamic: "",
        navshowbuttons: false,
        navthumbtitlecss: "display:block;position:relative;padding:2px 4px;text-align:left;font:bold 14px Arial,Helvetica,sans-serif;color:#333;",
        textpositionmarginbottom: 24,
        slide: {
            duration: 1000,
            easing: "easeOutCubic",
            checked: true
        },
        transition: "slide"
    });
});