package cellphoneshop.model;

// Generated Dec 10, 2013 11:05:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Binhluan generated by hbm2java
 */
public class Binhluan implements java.io.Serializable {

	private Long maBinhLuan;
	private Sanpham sanpham;
	private Nguoidung nguoidung;
	private String loiBinh;
	private Date ngayBinhLuan;

	public Binhluan() {
	}

	public Binhluan(Sanpham sanpham, Nguoidung nguoidung, String loiBinh,
			Date ngayBinhLuan) {
		this.sanpham = sanpham;
		this.nguoidung = nguoidung;
		this.loiBinh = loiBinh;
		this.ngayBinhLuan = ngayBinhLuan;
	}

	public Long getMaBinhLuan() {
		return this.maBinhLuan;
	}

	public void setMaBinhLuan(Long maBinhLuan) {
		this.maBinhLuan = maBinhLuan;
	}

	public Sanpham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(Sanpham sanpham) {
		this.sanpham = sanpham;
	}

	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	public String getLoiBinh() {
		return this.loiBinh;
	}

	public void setLoiBinh(String loiBinh) {
		this.loiBinh = loiBinh;
	}

	public Date getNgayBinhLuan() {
		return this.ngayBinhLuan;
	}

	public void setNgayBinhLuan(Date ngayBinhLuan) {
		this.ngayBinhLuan = ngayBinhLuan;
	}

}
