package cellphoneshop.model;
// Generated Jan 10, 2010 7:19:00 AM by Hibernate Tools 3.2.1.GA



/**
 * CtDonHang generated by hbm2java
 */
public class CtDonHang  implements java.io.Serializable {


     private Integer maCtdonHang;
     private SanPham sanPham;
     private DonHang donHang;
     private int giaTungSp;
     private int giamGiaTungSp;
     private int soLuong;
     private int tongGiaTri;

    public CtDonHang() {
    }

    public CtDonHang(SanPham sanPham, DonHang donHang, int giaTungSp, int giamGiaTungSp, int soLuong, int tongGiaTri) {
       this.sanPham = sanPham;
       this.donHang = donHang;
       this.giaTungSp = giaTungSp;
       this.giamGiaTungSp = giamGiaTungSp;
       this.soLuong = soLuong;
       this.tongGiaTri = tongGiaTri;
    }
   
    public Integer getMaCtdonHang() {
        return this.maCtdonHang;
    }
    
    public void setMaCtdonHang(Integer maCtdonHang) {
        this.maCtdonHang = maCtdonHang;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public DonHang getDonHang() {
        return this.donHang;
    }
    
    public void setDonHang(DonHang donHang) {
        this.donHang = donHang;
    }
    public int getGiaTungSp() {
        return this.giaTungSp;
    }
    
    public void setGiaTungSp(int giaTungSp) {
        this.giaTungSp = giaTungSp;
    }
    public int getGiamGiaTungSp() {
        return this.giamGiaTungSp;
    }
    
    public void setGiamGiaTungSp(int giamGiaTungSp) {
        this.giamGiaTungSp = giamGiaTungSp;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public int getTongGiaTri() {
        return this.tongGiaTri;
    }
    
    public void setTongGiaTri(int tongGiaTri) {
        this.tongGiaTri = tongGiaTri;
    }




}


