package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ctsanpham generated by hbm2java
 */
public class Ctsanpham implements java.io.Serializable {

	private Long maCtsp;
	private Thongsotainghe thongsotainghe;
	private Thongsodtdd thongsodtdd;
	private Thongsothenho thongsothenho;
	private Sanpham sanpham;
	private Thongsopin thongsopin;
	private Thongsosmartphone thongsosmartphone;
	private Thongsoadapter thongsoadapter;
	private Float trongLuong;
	private Float chieuCao;
	private Float chieuRong;
	private Float doDay;
	private Date ngaySx;
	private Set hinhanhsps = new HashSet(0);

	public Ctsanpham() {
	}

	public Ctsanpham(Sanpham sanpham) {
		this.sanpham = sanpham;
	}

	public Ctsanpham(Thongsotainghe thongsotainghe, Thongsodtdd thongsodtdd,
			Thongsothenho thongsothenho, Sanpham sanpham,
			Thongsopin thongsopin, Thongsosmartphone thongsosmartphone,
			Thongsoadapter thongsoadapter, Float trongLuong, Float chieuCao,
			Float chieuRong, Float doDay, Date ngaySx, Set hinhanhsps) {
		this.thongsotainghe = thongsotainghe;
		this.thongsodtdd = thongsodtdd;
		this.thongsothenho = thongsothenho;
		this.sanpham = sanpham;
		this.thongsopin = thongsopin;
		this.thongsosmartphone = thongsosmartphone;
		this.thongsoadapter = thongsoadapter;
		this.trongLuong = trongLuong;
		this.chieuCao = chieuCao;
		this.chieuRong = chieuRong;
		this.doDay = doDay;
		this.ngaySx = ngaySx;
		this.hinhanhsps = hinhanhsps;
	}

	public Long getMaCtsp() {
		return this.maCtsp;
	}

	public void setMaCtsp(Long maCtsp) {
		this.maCtsp = maCtsp;
	}

	public Thongsotainghe getThongsotainghe() {
		return this.thongsotainghe;
	}

	public void setThongsotainghe(Thongsotainghe thongsotainghe) {
		this.thongsotainghe = thongsotainghe;
	}

	public Thongsodtdd getThongsodtdd() {
		return this.thongsodtdd;
	}

	public void setThongsodtdd(Thongsodtdd thongsodtdd) {
		this.thongsodtdd = thongsodtdd;
	}

	public Thongsothenho getThongsothenho() {
		return this.thongsothenho;
	}

	public void setThongsothenho(Thongsothenho thongsothenho) {
		this.thongsothenho = thongsothenho;
	}

	public Sanpham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(Sanpham sanpham) {
		this.sanpham = sanpham;
	}

	public Thongsopin getThongsopin() {
		return this.thongsopin;
	}

	public void setThongsopin(Thongsopin thongsopin) {
		this.thongsopin = thongsopin;
	}

	public Thongsosmartphone getThongsosmartphone() {
		return this.thongsosmartphone;
	}

	public void setThongsosmartphone(Thongsosmartphone thongsosmartphone) {
		this.thongsosmartphone = thongsosmartphone;
	}

	public Thongsoadapter getThongsoadapter() {
		return this.thongsoadapter;
	}

	public void setThongsoadapter(Thongsoadapter thongsoadapter) {
		this.thongsoadapter = thongsoadapter;
	}

	public Float getTrongLuong() {
		return this.trongLuong;
	}

	public void setTrongLuong(Float trongLuong) {
		this.trongLuong = trongLuong;
	}

	public Float getChieuCao() {
		return this.chieuCao;
	}

	public void setChieuCao(Float chieuCao) {
		this.chieuCao = chieuCao;
	}

	public Float getChieuRong() {
		return this.chieuRong;
	}

	public void setChieuRong(Float chieuRong) {
		this.chieuRong = chieuRong;
	}

	public Float getDoDay() {
		return this.doDay;
	}

	public void setDoDay(Float doDay) {
		this.doDay = doDay;
	}

	public Date getNgaySx() {
		return this.ngaySx;
	}

	public void setNgaySx(Date ngaySx) {
		this.ngaySx = ngaySx;
	}

	public Set getHinhanhsps() {
		return this.hinhanhsps;
	}

	public void setHinhanhsps(Set hinhanhsps) {
		this.hinhanhsps = hinhanhsps;
	}

}
