package cellphoneshop.model;

// Generated Dec 10, 2013 11:05:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ctsanpham generated by hbm2java
 */
public class Ctsanpham implements java.io.Serializable {

	private Long maCtsp;
	private Sanpham sanpham;
	private Float trongLuong;
	private Float chieuCao;
	private Float chieuRong;
	private Float doDay;
	private Date ngaySx;
	private Set thongsoadapters = new HashSet(0);
	private Set thongsosmartphones = new HashSet(0);
	private Set hinhanhsps = new HashSet(0);
	private Set thongsotainghes = new HashSet(0);
	private Set thongsopins = new HashSet(0);
	private Set thongsodtdds = new HashSet(0);
	private Set thongsothenhos = new HashSet(0);

	public Ctsanpham() {
	}

	public Ctsanpham(Sanpham sanpham) {
		this.sanpham = sanpham;
	}

	public Ctsanpham(Sanpham sanpham, Float trongLuong, Float chieuCao,
			Float chieuRong, Float doDay, Date ngaySx, Set thongsoadapters,
			Set thongsosmartphones, Set hinhanhsps, Set thongsotainghes,
			Set thongsopins, Set thongsodtdds, Set thongsothenhos) {
		this.sanpham = sanpham;
		this.trongLuong = trongLuong;
		this.chieuCao = chieuCao;
		this.chieuRong = chieuRong;
		this.doDay = doDay;
		this.ngaySx = ngaySx;
		this.thongsoadapters = thongsoadapters;
		this.thongsosmartphones = thongsosmartphones;
		this.hinhanhsps = hinhanhsps;
		this.thongsotainghes = thongsotainghes;
		this.thongsopins = thongsopins;
		this.thongsodtdds = thongsodtdds;
		this.thongsothenhos = thongsothenhos;
	}

	public Long getMaCtsp() {
		return this.maCtsp;
	}

	public void setMaCtsp(Long maCtsp) {
		this.maCtsp = maCtsp;
	}

	public Sanpham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(Sanpham sanpham) {
		this.sanpham = sanpham;
	}

	public Float getTrongLuong() {
		return this.trongLuong;
	}

	public void setTrongLuong(Float trongLuong) {
		this.trongLuong = trongLuong;
	}

	public Float getChieuCao() {
		return this.chieuCao;
	}

	public void setChieuCao(Float chieuCao) {
		this.chieuCao = chieuCao;
	}

	public Float getChieuRong() {
		return this.chieuRong;
	}

	public void setChieuRong(Float chieuRong) {
		this.chieuRong = chieuRong;
	}

	public Float getDoDay() {
		return this.doDay;
	}

	public void setDoDay(Float doDay) {
		this.doDay = doDay;
	}

	public Date getNgaySx() {
		return this.ngaySx;
	}

	public void setNgaySx(Date ngaySx) {
		this.ngaySx = ngaySx;
	}

	public Set getThongsoadapters() {
		return this.thongsoadapters;
	}

	public void setThongsoadapters(Set thongsoadapters) {
		this.thongsoadapters = thongsoadapters;
	}

	public Set getThongsosmartphones() {
		return this.thongsosmartphones;
	}

	public void setThongsosmartphones(Set thongsosmartphones) {
		this.thongsosmartphones = thongsosmartphones;
	}

	public Set getHinhanhsps() {
		return this.hinhanhsps;
	}

	public void setHinhanhsps(Set hinhanhsps) {
		this.hinhanhsps = hinhanhsps;
	}

	public Set getThongsotainghes() {
		return this.thongsotainghes;
	}

	public void setThongsotainghes(Set thongsotainghes) {
		this.thongsotainghes = thongsotainghes;
	}

	public Set getThongsopins() {
		return this.thongsopins;
	}

	public void setThongsopins(Set thongsopins) {
		this.thongsopins = thongsopins;
	}

	public Set getThongsodtdds() {
		return this.thongsodtdds;
	}

	public void setThongsodtdds(Set thongsodtdds) {
		this.thongsodtdds = thongsodtdds;
	}

	public Set getThongsothenhos() {
		return this.thongsothenhos;
	}

	public void setThongsothenhos(Set thongsothenhos) {
		this.thongsothenhos = thongsothenhos;
	}

}
