package cellphoneshop.model;
// Generated Jan 10, 2010 7:19:00 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CtSanPham generated by hbm2java
 */
public class CtSanPham  implements java.io.Serializable {

     private Integer maCtsp;
     private SanPham sanPham;
     private HeDieuHanh heDieuHanh;
     private Float trongLuong;
     private Float chieuCao;
     private Float chieuRong;
     private Float doDay;
     private Date ngaySx;
     private String loaiManhinh;
     private String soMauManHinh;
     private String doPhanGiaiManHinh;
     private String chuanManHinh;
     private Float kichThuocManHinh;
     private String camUng;
     private String matDoDiemAnh;
     private String cameraSau;
     private String cameraTruoc;
     private String tinhNangCamera;
     private String quayPhim;
     private Boolean videoCall;
     private Float tocDoCpu;
     private Integer soNhanCpu;
     private String chipset;
     private String ram;
     private String gpu;
     private String boNhoTrong;
     private String theNhoNgoai;
     private Integer dungLuongTheToiDa;
     private Float dungLuongPin;
     private String congNghePin;
     private Boolean pinCoTheThaoRoi;
     private Float thoiGianChoToiDa;
     private Float thoiGianChoQuayPhim;
     private Float thoiGianChoGoiDien;
     private String loaiBanPhim;
     private Integer soLuongSim;
     private String mang2g;
     private String mang3g;
     private String mang4g;
     private String wifi;
     private String bluetooth;
     private String gprs;
     private String gps;
     private String boCamBien;
     private String denFlash;
     private String denPin;
     private Set hinhAnhSps = new HashSet(0);

    public CtSanPham() {
    }

	
    public CtSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public CtSanPham(SanPham sanPham, HeDieuHanh heDieuHanh, Float trongLuong, Float chieuCao, Float chieuRong, Float doDay, Date ngaySx, String loaiManhinh, String soMauManHinh, String doPhanGiaiManHinh, String chuanManHinh, Float kichThuocManHinh, String camUng, String matDoDiemAnh, String cameraSau, String cameraTruoc, String tinhNangCamera, String quayPhim, Boolean videoCall, Float tocDoCpu, Integer soNhanCpu, String chipset, String ram, String gpu, String boNhoTrong, String theNhoNgoai, Integer dungLuongTheToiDa, Float dungLuongPin, String congNghePin, Boolean pinCoTheThaoRoi, Float thoiGianChoToiDa, Float thoiGianChoQuayPhim, Float thoiGianChoGoiDien, String loaiBanPhim, Integer soLuongSim, String mang2g, String mang3g, String mang4g, String wifi, String bluetooth, String gprs, String gps, String boCamBien, String denFlash, String denPin, Set hinhAnhSps) {
       this.sanPham = sanPham;
       this.heDieuHanh = heDieuHanh;
       this.trongLuong = trongLuong;
       this.chieuCao = chieuCao;
       this.chieuRong = chieuRong;
       this.doDay = doDay;
       this.ngaySx = ngaySx;
       this.loaiManhinh = loaiManhinh;
       this.soMauManHinh = soMauManHinh;
       this.doPhanGiaiManHinh = doPhanGiaiManHinh;
       this.chuanManHinh = chuanManHinh;
       this.kichThuocManHinh = kichThuocManHinh;
       this.camUng = camUng;
       this.matDoDiemAnh = matDoDiemAnh;
       this.cameraSau = cameraSau;
       this.cameraTruoc = cameraTruoc;
       this.tinhNangCamera = tinhNangCamera;
       this.quayPhim = quayPhim;
       this.videoCall = videoCall;
       this.tocDoCpu = tocDoCpu;
       this.soNhanCpu = soNhanCpu;
       this.chipset = chipset;
       this.ram = ram;
       this.gpu = gpu;
       this.boNhoTrong = boNhoTrong;
       this.theNhoNgoai = theNhoNgoai;
       this.dungLuongTheToiDa = dungLuongTheToiDa;
       this.dungLuongPin = dungLuongPin;
       this.congNghePin = congNghePin;
       this.pinCoTheThaoRoi = pinCoTheThaoRoi;
       this.thoiGianChoToiDa = thoiGianChoToiDa;
       this.thoiGianChoQuayPhim = thoiGianChoQuayPhim;
       this.thoiGianChoGoiDien = thoiGianChoGoiDien;
       this.loaiBanPhim = loaiBanPhim;
       this.soLuongSim = soLuongSim;
       this.mang2g = mang2g;
       this.mang3g = mang3g;
       this.mang4g = mang4g;
       this.wifi = wifi;
       this.bluetooth = bluetooth;
       this.gprs = gprs;
       this.gps = gps;
       this.boCamBien = boCamBien;
       this.denFlash = denFlash;
       this.denPin = denPin;
       this.hinhAnhSps = hinhAnhSps;
    }
   
    public Integer getMaCtsp() {
        return this.maCtsp;
    }
    
    public void setMaCtsp(Integer maCtsp) {
        this.maCtsp = maCtsp;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public HeDieuHanh getHeDieuHanh() {
        return this.heDieuHanh;
    }
    
    public void setHeDieuHanh(HeDieuHanh heDieuHanh) {
        this.heDieuHanh = heDieuHanh;
    }
    public Float getTrongLuong() {
        return this.trongLuong;
    }
    
    public void setTrongLuong(Float trongLuong) {
        this.trongLuong = trongLuong;
    }
    public Float getChieuCao() {
        return this.chieuCao;
    }
    
    public void setChieuCao(Float chieuCao) {
        this.chieuCao = chieuCao;
    }
    public Float getChieuRong() {
        return this.chieuRong;
    }
    
    public void setChieuRong(Float chieuRong) {
        this.chieuRong = chieuRong;
    }
    public Float getDoDay() {
        return this.doDay;
    }
    
    public void setDoDay(Float doDay) {
        this.doDay = doDay;
    }
    public Date getNgaySx() {
        return this.ngaySx;
    }
    
    public void setNgaySx(Date ngaySx) {
        this.ngaySx = ngaySx;
    }
    public String getLoaiManhinh() {
        return this.loaiManhinh;
    }
    
    public void setLoaiManhinh(String loaiManhinh) {
        this.loaiManhinh = loaiManhinh;
    }
    public String getSoMauManHinh() {
        return this.soMauManHinh;
    }
    
    public void setSoMauManHinh(String soMauManHinh) {
        this.soMauManHinh = soMauManHinh;
    }
    public String getDoPhanGiaiManHinh() {
        return this.doPhanGiaiManHinh;
    }
    
    public void setDoPhanGiaiManHinh(String doPhanGiaiManHinh) {
        this.doPhanGiaiManHinh = doPhanGiaiManHinh;
    }
    public String getChuanManHinh() {
        return this.chuanManHinh;
    }
    
    public void setChuanManHinh(String chuanManHinh) {
        this.chuanManHinh = chuanManHinh;
    }
    public Float getKichThuocManHinh() {
        return this.kichThuocManHinh;
    }
    
    public void setKichThuocManHinh(Float kichThuocManHinh) {
        this.kichThuocManHinh = kichThuocManHinh;
    }
    public String getCamUng() {
        return this.camUng;
    }
    
    public void setCamUng(String camUng) {
        this.camUng = camUng;
    }
    public String getMatDoDiemAnh() {
        return this.matDoDiemAnh;
    }
    
    public void setMatDoDiemAnh(String matDoDiemAnh) {
        this.matDoDiemAnh = matDoDiemAnh;
    }
    public String getCameraSau() {
        return this.cameraSau;
    }
    
    public void setCameraSau(String cameraSau) {
        this.cameraSau = cameraSau;
    }
    public String getCameraTruoc() {
        return this.cameraTruoc;
    }
    
    public void setCameraTruoc(String cameraTruoc) {
        this.cameraTruoc = cameraTruoc;
    }
    public String getTinhNangCamera() {
        return this.tinhNangCamera;
    }
    
    public void setTinhNangCamera(String tinhNangCamera) {
        this.tinhNangCamera = tinhNangCamera;
    }
    public String getQuayPhim() {
        return this.quayPhim;
    }
    
    public void setQuayPhim(String quayPhim) {
        this.quayPhim = quayPhim;
    }
    public Boolean getVideoCall() {
        return this.videoCall;
    }
    
    public void setVideoCall(Boolean videoCall) {
        this.videoCall = videoCall;
    }
    public Float getTocDoCpu() {
        return this.tocDoCpu;
    }
    
    public void setTocDoCpu(Float tocDoCpu) {
        this.tocDoCpu = tocDoCpu;
    }
    public Integer getSoNhanCpu() {
        return this.soNhanCpu;
    }
    
    public void setSoNhanCpu(Integer soNhanCpu) {
        this.soNhanCpu = soNhanCpu;
    }
    public String getChipset() {
        return this.chipset;
    }
    
    public void setChipset(String chipset) {
        this.chipset = chipset;
    }
    public String getRam() {
        return this.ram;
    }
    
    public void setRam(String ram) {
        this.ram = ram;
    }
    public String getGpu() {
        return this.gpu;
    }
    
    public void setGpu(String gpu) {
        this.gpu = gpu;
    }
    public String getBoNhoTrong() {
        return this.boNhoTrong;
    }
    
    public void setBoNhoTrong(String boNhoTrong) {
        this.boNhoTrong = boNhoTrong;
    }
    public String getTheNhoNgoai() {
        return this.theNhoNgoai;
    }
    
    public void setTheNhoNgoai(String theNhoNgoai) {
        this.theNhoNgoai = theNhoNgoai;
    }
    public Integer getDungLuongTheToiDa() {
        return this.dungLuongTheToiDa;
    }
    
    public void setDungLuongTheToiDa(Integer dungLuongTheToiDa) {
        this.dungLuongTheToiDa = dungLuongTheToiDa;
    }
    public Float getDungLuongPin() {
        return this.dungLuongPin;
    }
    
    public void setDungLuongPin(Float dungLuongPin) {
        this.dungLuongPin = dungLuongPin;
    }
    public String getCongNghePin() {
        return this.congNghePin;
    }
    
    public void setCongNghePin(String congNghePin) {
        this.congNghePin = congNghePin;
    }
    public Boolean getPinCoTheThaoRoi() {
        return this.pinCoTheThaoRoi;
    }
    
    public void setPinCoTheThaoRoi(Boolean pinCoTheThaoRoi) {
        this.pinCoTheThaoRoi = pinCoTheThaoRoi;
    }
    public Float getThoiGianChoToiDa() {
        return this.thoiGianChoToiDa;
    }
    
    public void setThoiGianChoToiDa(Float thoiGianChoToiDa) {
        this.thoiGianChoToiDa = thoiGianChoToiDa;
    }
    public Float getThoiGianChoQuayPhim() {
        return this.thoiGianChoQuayPhim;
    }
    
    public void setThoiGianChoQuayPhim(Float thoiGianChoQuayPhim) {
        this.thoiGianChoQuayPhim = thoiGianChoQuayPhim;
    }
    public Float getThoiGianChoGoiDien() {
        return this.thoiGianChoGoiDien;
    }
    
    public void setThoiGianChoGoiDien(Float thoiGianChoGoiDien) {
        this.thoiGianChoGoiDien = thoiGianChoGoiDien;
    }
    public String getLoaiBanPhim() {
        return this.loaiBanPhim;
    }
    
    public void setLoaiBanPhim(String loaiBanPhim) {
        this.loaiBanPhim = loaiBanPhim;
    }
    public Integer getSoLuongSim() {
        return this.soLuongSim;
    }
    
    public void setSoLuongSim(Integer soLuongSim) {
        this.soLuongSim = soLuongSim;
    }
    public String getMang2g() {
        return this.mang2g;
    }
    
    public void setMang2g(String mang2g) {
        this.mang2g = mang2g;
    }
    public String getMang3g() {
        return this.mang3g;
    }
    
    public void setMang3g(String mang3g) {
        this.mang3g = mang3g;
    }
    public String getMang4g() {
        return this.mang4g;
    }
    
    public void setMang4g(String mang4g) {
        this.mang4g = mang4g;
    }
    public String getWifi() {
        return this.wifi;
    }
    
    public void setWifi(String wifi) {
        this.wifi = wifi;
    }
    public String getBluetooth() {
        return this.bluetooth;
    }
    
    public void setBluetooth(String bluetooth) {
        this.bluetooth = bluetooth;
    }
    public String getGprs() {
        return this.gprs;
    }
    
    public void setGprs(String gprs) {
        this.gprs = gprs;
    }
    public String getGps() {
        return this.gps;
    }
    
    public void setGps(String gps) {
        this.gps = gps;
    }
    public String getBoCamBien() {
        return this.boCamBien;
    }
    
    public void setBoCamBien(String boCamBien) {
        this.boCamBien = boCamBien;
    }
    public String getDenFlash() {
        return this.denFlash;
    }
    
    public void setDenFlash(String denFlash) {
        this.denFlash = denFlash;
    }
    public String getDenPin() {
        return this.denPin;
    }
    
    public void setDenPin(String denPin) {
        this.denPin = denPin;
    }
    public Set getHinhAnhSps() {
        return this.hinhAnhSps;
    }
    
    public void setHinhAnhSps(Set hinhAnhSps) {
        this.hinhAnhSps = hinhAnhSps;
    }




}


