package cellphoneshop.model;
// Generated Jan 10, 2010 7:19:00 AM by Hibernate Tools 3.2.1.GA



/**
 * DanhGia generated by hbm2java
 */
public class DanhGia  implements java.io.Serializable {


     private DanhGiaId id;
     private SanPham sanPham;
     private NguoiDung nguoiDung;
     private float diem;

    public DanhGia() {
    }

    public DanhGia(DanhGiaId id, SanPham sanPham, NguoiDung nguoiDung, float diem) {
       this.id = id;
       this.sanPham = sanPham;
       this.nguoiDung = nguoiDung;
       this.diem = diem;
    }
   
    public DanhGiaId getId() {
        return this.id;
    }
    
    public void setId(DanhGiaId id) {
        this.id = id;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public NguoiDung getNguoiDung() {
        return this.nguoiDung;
    }
    
    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }
    public float getDiem() {
        return this.diem;
    }
    
    public void setDiem(float diem) {
        this.diem = diem;
    }




}


