package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

/**
 * Danhgia generated by hbm2java
 */
public class Danhgia implements java.io.Serializable {

	private DanhgiaId id;
	private Sanpham sanpham;
	private Nguoidung nguoidung;
	private float diem;

	public Danhgia() {
	}

	public Danhgia(DanhgiaId id, Sanpham sanpham, Nguoidung nguoidung,
			float diem) {
		this.id = id;
		this.sanpham = sanpham;
		this.nguoidung = nguoidung;
		this.diem = diem;
	}

	public DanhgiaId getId() {
		return this.id;
	}

	public void setId(DanhgiaId id) {
		this.id = id;
	}

	public Sanpham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(Sanpham sanpham) {
		this.sanpham = sanpham;
	}

	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	public float getDiem() {
		return this.diem;
	}

	public void setDiem(float diem) {
		this.diem = diem;
	}

}
