package cellphoneshop.model;
// Generated Jan 10, 2010 7:19:00 AM by Hibernate Tools 3.2.1.GA



/**
 * DanhGiaId generated by hbm2java
 */
public class DanhGiaId  implements java.io.Serializable {


     private int maSp;
     private int maNd;

    public DanhGiaId() {
    }

    public DanhGiaId(int maSp, int maNd) {
       this.maSp = maSp;
       this.maNd = maNd;
    }
   
    public int getMaSp() {
        return this.maSp;
    }
    
    public void setMaSp(int maSp) {
        this.maSp = maSp;
    }
    public int getMaNd() {
        return this.maNd;
    }
    
    public void setMaNd(int maNd) {
        this.maNd = maNd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DanhGiaId) ) return false;
		 DanhGiaId castOther = ( DanhGiaId ) other; 
         
		 return (this.getMaSp()==castOther.getMaSp())
 && (this.getMaNd()==castOther.getMaNd());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMaSp();
         result = 37 * result + this.getMaNd();
         return result;
   }   


}


