package cellphoneshop.model;

// Generated Dec 10, 2013 11:05:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * DanhgiaId generated by hbm2java
 */
public class DanhgiaId implements java.io.Serializable {

	private long maSp;
	private int maNd;

	public DanhgiaId() {
	}

	public DanhgiaId(long maSp, int maNd) {
		this.maSp = maSp;
		this.maNd = maNd;
	}

	public long getMaSp() {
		return this.maSp;
	}

	public void setMaSp(long maSp) {
		this.maSp = maSp;
	}

	public int getMaNd() {
		return this.maNd;
	}

	public void setMaNd(int maNd) {
		this.maNd = maNd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DanhgiaId))
			return false;
		DanhgiaId castOther = (DanhgiaId) other;

		return (this.getMaSp() == castOther.getMaSp())
				&& (this.getMaNd() == castOther.getMaNd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMaSp();
		result = 37 * result + this.getMaNd();
		return result;
	}

}
