package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Donhang generated by hbm2java
 */
public class Donhang implements java.io.Serializable {

	private Long maDonHang;
	private Ptgiaohang ptgiaohang;
	private Nguoidung nguoidung;
	private Trangthaidonhang trangthaidonhang;
	private Date ngayDatHang;
	private int tongGiaTri;
	private Integer giamGia;
	private String diaChiGiaoHang;
	private Set phieugiaohangs = new HashSet(0);
	private Set ctdonhangs = new HashSet(0);

	public Donhang() {
	}

	public Donhang(Ptgiaohang ptgiaohang, Nguoidung nguoidung,
			Trangthaidonhang trangthaidonhang, Date ngayDatHang, int tongGiaTri) {
		this.ptgiaohang = ptgiaohang;
		this.nguoidung = nguoidung;
		this.trangthaidonhang = trangthaidonhang;
		this.ngayDatHang = ngayDatHang;
		this.tongGiaTri = tongGiaTri;
	}

	public Donhang(Ptgiaohang ptgiaohang, Nguoidung nguoidung,
			Trangthaidonhang trangthaidonhang, Date ngayDatHang,
			int tongGiaTri, Integer giamGia, String diaChiGiaoHang,
			Set phieugiaohangs, Set ctdonhangs) {
		this.ptgiaohang = ptgiaohang;
		this.nguoidung = nguoidung;
		this.trangthaidonhang = trangthaidonhang;
		this.ngayDatHang = ngayDatHang;
		this.tongGiaTri = tongGiaTri;
		this.giamGia = giamGia;
		this.diaChiGiaoHang = diaChiGiaoHang;
		this.phieugiaohangs = phieugiaohangs;
		this.ctdonhangs = ctdonhangs;
	}

	public Long getMaDonHang() {
		return this.maDonHang;
	}

	public void setMaDonHang(Long maDonHang) {
		this.maDonHang = maDonHang;
	}

	public Ptgiaohang getPtgiaohang() {
		return this.ptgiaohang;
	}

	public void setPtgiaohang(Ptgiaohang ptgiaohang) {
		this.ptgiaohang = ptgiaohang;
	}

	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	public Trangthaidonhang getTrangthaidonhang() {
		return this.trangthaidonhang;
	}

	public void setTrangthaidonhang(Trangthaidonhang trangthaidonhang) {
		this.trangthaidonhang = trangthaidonhang;
	}

	public Date getNgayDatHang() {
		return this.ngayDatHang;
	}

	public void setNgayDatHang(Date ngayDatHang) {
		this.ngayDatHang = ngayDatHang;
	}

	public int getTongGiaTri() {
		return this.tongGiaTri;
	}

	public void setTongGiaTri(int tongGiaTri) {
		this.tongGiaTri = tongGiaTri;
	}

	public Integer getGiamGia() {
		return this.giamGia;
	}

	public void setGiamGia(Integer giamGia) {
		this.giamGia = giamGia;
	}

	public String getDiaChiGiaoHang() {
		return this.diaChiGiaoHang;
	}

	public void setDiaChiGiaoHang(String diaChiGiaoHang) {
		this.diaChiGiaoHang = diaChiGiaoHang;
	}

	public Set getPhieugiaohangs() {
		return this.phieugiaohangs;
	}

	public void setPhieugiaohangs(Set phieugiaohangs) {
		this.phieugiaohangs = phieugiaohangs;
	}

	public Set getCtdonhangs() {
		return this.ctdonhangs;
	}

	public void setCtdonhangs(Set ctdonhangs) {
		this.ctdonhangs = ctdonhangs;
	}

}
