package cellphoneshop.model;
// Generated Jan 10, 2010 8:52:59 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DonHang generated by hbm2java
 */
public class DonHang  implements java.io.Serializable {


     private Integer maDonHang;
     private PtThanhToan ptThanhToan;
     private PtGiaoHang ptGiaoHang;
     private NguoiDung nguoiDung;
     private NguoiNhan nguoiNhan;
     private TrangThaiDonHang trangThaiDonHang;
     private Date ngayDatHang;
     private int tongGiaTri;
     private Integer giamGia;
     private Set phieuGiaoHangs = new HashSet(0);
     private Set ctDonHangs = new HashSet(0);

    public DonHang() {
    }

	
    public DonHang(PtThanhToan ptThanhToan, PtGiaoHang ptGiaoHang, NguoiDung nguoiDung, NguoiNhan nguoiNhan, TrangThaiDonHang trangThaiDonHang, Date ngayDatHang, int tongGiaTri) {
        this.ptThanhToan = ptThanhToan;
        this.ptGiaoHang = ptGiaoHang;
        this.nguoiDung = nguoiDung;
        this.nguoiNhan = nguoiNhan;
        this.trangThaiDonHang = trangThaiDonHang;
        this.ngayDatHang = ngayDatHang;
        this.tongGiaTri = tongGiaTri;
    }
    public DonHang(PtThanhToan ptThanhToan, PtGiaoHang ptGiaoHang, NguoiDung nguoiDung, NguoiNhan nguoiNhan, TrangThaiDonHang trangThaiDonHang, Date ngayDatHang, int tongGiaTri, Integer giamGia, Set phieuGiaoHangs, Set ctDonHangs) {
       this.ptThanhToan = ptThanhToan;
       this.ptGiaoHang = ptGiaoHang;
       this.nguoiDung = nguoiDung;
       this.nguoiNhan = nguoiNhan;
       this.trangThaiDonHang = trangThaiDonHang;
       this.ngayDatHang = ngayDatHang;
       this.tongGiaTri = tongGiaTri;
       this.giamGia = giamGia;
       this.phieuGiaoHangs = phieuGiaoHangs;
       this.ctDonHangs = ctDonHangs;
    }
   
    public Integer getMaDonHang() {
        return this.maDonHang;
    }
    
    public void setMaDonHang(Integer maDonHang) {
        this.maDonHang = maDonHang;
    }
    public PtThanhToan getPtThanhToan() {
        return this.ptThanhToan;
    }
    
    public void setPtThanhToan(PtThanhToan ptThanhToan) {
        this.ptThanhToan = ptThanhToan;
    }
    public PtGiaoHang getPtGiaoHang() {
        return this.ptGiaoHang;
    }
    
    public void setPtGiaoHang(PtGiaoHang ptGiaoHang) {
        this.ptGiaoHang = ptGiaoHang;
    }
    public NguoiDung getNguoiDung() {
        return this.nguoiDung;
    }
    
    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }
    public NguoiNhan getNguoiNhan() {
        return this.nguoiNhan;
    }
    
    public void setNguoiNhan(NguoiNhan nguoiNhan) {
        this.nguoiNhan = nguoiNhan;
    }
    public TrangThaiDonHang getTrangThaiDonHang() {
        return this.trangThaiDonHang;
    }
    
    public void setTrangThaiDonHang(TrangThaiDonHang trangThaiDonHang) {
        this.trangThaiDonHang = trangThaiDonHang;
    }
    public Date getNgayDatHang() {
        return this.ngayDatHang;
    }
    
    public void setNgayDatHang(Date ngayDatHang) {
        this.ngayDatHang = ngayDatHang;
    }
    public int getTongGiaTri() {
        return this.tongGiaTri;
    }
    
    public void setTongGiaTri(int tongGiaTri) {
        this.tongGiaTri = tongGiaTri;
    }
    public Integer getGiamGia() {
        return this.giamGia;
    }
    
    public void setGiamGia(Integer giamGia) {
        this.giamGia = giamGia;
    }
    public Set getPhieuGiaoHangs() {
        return this.phieuGiaoHangs;
    }
    
    public void setPhieuGiaoHangs(Set phieuGiaoHangs) {
        this.phieuGiaoHangs = phieuGiaoHangs;
    }
    public Set getCtDonHangs() {
        return this.ctDonHangs;
    }
    
    public void setCtDonHangs(Set ctDonHangs) {
        this.ctDonHangs = ctDonHangs;
    }




}


