package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Hedieuhanh generated by hbm2java
 */
public class Hedieuhanh implements java.io.Serializable {

	private Short maHdh;
	private String tenHdh;
	private Set thongsosmartphones = new HashSet(0);

	public Hedieuhanh() {
	}

	public Hedieuhanh(String tenHdh) {
		this.tenHdh = tenHdh;
	}

	public Hedieuhanh(String tenHdh, Set thongsosmartphones) {
		this.tenHdh = tenHdh;
		this.thongsosmartphones = thongsosmartphones;
	}

	public Short getMaHdh() {
		return this.maHdh;
	}

	public void setMaHdh(Short maHdh) {
		this.maHdh = maHdh;
	}

	public String getTenHdh() {
		return this.tenHdh;
	}

	public void setTenHdh(String tenHdh) {
		this.tenHdh = tenHdh;
	}

	public Set getThongsosmartphones() {
		return this.thongsosmartphones;
	}

	public void setThongsosmartphones(Set thongsosmartphones) {
		this.thongsosmartphones = thongsosmartphones;
	}

}
