package cellphoneshop.model;
// Generated Jan 10, 2010 7:19:00 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * HeDieuHanh generated by hbm2java
 */
public class HeDieuHanh  implements java.io.Serializable {


     private Integer maHdh;
     private String tenHdh;
     private Set ctSanPhams = new HashSet(0);

    public HeDieuHanh() {
    }

	
    public HeDieuHanh(String tenHdh) {
        this.tenHdh = tenHdh;
    }
    public HeDieuHanh(String tenHdh, Set ctSanPhams) {
       this.tenHdh = tenHdh;
       this.ctSanPhams = ctSanPhams;
    }
   
    public Integer getMaHdh() {
        return this.maHdh;
    }
    
    public void setMaHdh(Integer maHdh) {
        this.maHdh = maHdh;
    }
    public String getTenHdh() {
        return this.tenHdh;
    }
    
    public void setTenHdh(String tenHdh) {
        this.tenHdh = tenHdh;
    }
    public Set getCtSanPhams() {
        return this.ctSanPhams;
    }
    
    public void setCtSanPhams(Set ctSanPhams) {
        this.ctSanPhams = ctSanPhams;
    }




}


