package cellphoneshop.model;

// Generated Dec 10, 2013 11:05:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * Hinhanhsp generated by hbm2java
 */
public class Hinhanhsp implements java.io.Serializable {

	private Long maHinhAnh;
	private Ctsanpham ctsanpham;
	private String duongDan;
	private short stt;

	public Hinhanhsp() {
	}

	public Hinhanhsp(Ctsanpham ctsanpham, String duongDan, short stt) {
		this.ctsanpham = ctsanpham;
		this.duongDan = duongDan;
		this.stt = stt;
	}

	public Long getMaHinhAnh() {
		return this.maHinhAnh;
	}

	public void setMaHinhAnh(Long maHinhAnh) {
		this.maHinhAnh = maHinhAnh;
	}

	public Ctsanpham getCtsanpham() {
		return this.ctsanpham;
	}

	public void setCtsanpham(Ctsanpham ctsanpham) {
		this.ctsanpham = ctsanpham;
	}

	public String getDuongDan() {
		return this.duongDan;
	}

	public void setDuongDan(String duongDan) {
		this.duongDan = duongDan;
	}

	public short getStt() {
		return this.stt;
	}

	public void setStt(short stt) {
		this.stt = stt;
	}

}
