package cellphoneshop.model;
// Generated Dec 20, 2013 12:09:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KhuyenMai generated by hbm2java
 */
public class KhuyenMai  implements java.io.Serializable {
     private Integer maKm;
     private TrangThaiKhuyenMai trangThaiKhuyenMai;
     private String tieuDe;
     private String moTa;
     private Float phanTramGiamGia;
     private Date ngayBatDau;
     private Date ngayKetThuc;
     private String quaTang;
     private String hinhAnh;
     private Set sanPhams = new HashSet(0);

    public KhuyenMai() {
    }

	
    public KhuyenMai(TrangThaiKhuyenMai trangThaiKhuyenMai) {
        this.trangThaiKhuyenMai = trangThaiKhuyenMai;
    }
    public KhuyenMai(TrangThaiKhuyenMai trangThaiKhuyenMai, String tieuDe, String moTa, Float phanTramGiamGia, Date ngayBatDau, Date ngayKetThuc, String quaTang, Set sanPhams) {
       this.trangThaiKhuyenMai = trangThaiKhuyenMai;
       this.tieuDe = tieuDe;
       this.moTa = moTa;
       this.phanTramGiamGia = phanTramGiamGia;
       this.ngayBatDau = ngayBatDau;
       this.ngayKetThuc = ngayKetThuc;
       this.quaTang = quaTang;
       this.sanPhams = sanPhams;
    }
   
    public Integer getMaKm() {
        return this.maKm;
    }
    
    public void setMaKm(Integer maKm) {
        this.maKm = maKm;
    }
    public TrangThaiKhuyenMai getTrangThaiKhuyenMai() {
        return this.trangThaiKhuyenMai;
    }
    
    public void setTrangThaiKhuyenMai(TrangThaiKhuyenMai trangThaiKhuyenMai) {
        this.trangThaiKhuyenMai = trangThaiKhuyenMai;
    }
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public Float getPhanTramGiamGia() {
        return this.phanTramGiamGia;
    }
    
    public void setPhanTramGiamGia(Float phanTramGiamGia) {
        this.phanTramGiamGia = phanTramGiamGia;
    }
    public Date getNgayBatDau() {
        return this.ngayBatDau;
    }
    
    public void setNgayBatDau(Date ngayBatDau) {
        this.ngayBatDau = ngayBatDau;
    }
    public Date getNgayKetThuc() {
        return this.ngayKetThuc;
    }
    
    public void setNgayKetThuc(Date ngayKetThuc) {
        this.ngayKetThuc = ngayKetThuc;
    }
    public String getQuaTang() {
        return this.quaTang;
    }
    
    public void setQuaTang(String quaTang) {
        this.quaTang = quaTang;
    }
    public Set getSanPhams() {
        return this.sanPhams;
    }
    
    public void setSanPhams(Set sanPhams) {
        this.sanPhams = sanPhams;
    }

	public String getHinhAnh() {
		return hinhAnh;
	}
	
	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}
    
}


