package cellphoneshop.model;
// Generated Jan 10, 2010 7:19:00 AM by Hibernate Tools 3.2.1.GA



/**
 * LienHe generated by hbm2java
 */
public class LienHe  implements java.io.Serializable {


     private int maLienHe;
     private String email;
     private String hoTen;
     private String noiDung;

    public LienHe() {
    }

    public LienHe(int maLienHe, String email, String hoTen, String noiDung) {
       this.maLienHe = maLienHe;
       this.email = email;
       this.hoTen = hoTen;
       this.noiDung = noiDung;
    }
   
    public int getMaLienHe() {
        return this.maLienHe;
    }
    
    public void setMaLienHe(int maLienHe) {
        this.maLienHe = maLienHe;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }




}


