package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Loaisanpham generated by hbm2java
 */
public class Loaisanpham implements java.io.Serializable {

	private Short maLoaiSp;
	private String tenLoaiSp;
	private Set sanphams = new HashSet(0);

	public Loaisanpham() {
	}

	public Loaisanpham(String tenLoaiSp) {
		this.tenLoaiSp = tenLoaiSp;
	}

	public Loaisanpham(String tenLoaiSp, Set sanphams) {
		this.tenLoaiSp = tenLoaiSp;
		this.sanphams = sanphams;
	}

	public Short getMaLoaiSp() {
		return this.maLoaiSp;
	}

	public void setMaLoaiSp(Short maLoaiSp) {
		this.maLoaiSp = maLoaiSp;
	}

	public String getTenLoaiSp() {
		return this.tenLoaiSp;
	}

	public void setTenLoaiSp(String tenLoaiSp) {
		this.tenLoaiSp = tenLoaiSp;
	}

	public Set getSanphams() {
		return this.sanphams;
	}

	public void setSanphams(Set sanphams) {
		this.sanphams = sanphams;
	}

}
