package cellphoneshop.model;
// Generated Jan 10, 2010 7:19:00 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * LoaiSanPham generated by hbm2java
 */
public class LoaiSanPham  implements java.io.Serializable {


     private Integer maLoaiSp;
     private String tenLoaiSp;
     private Set sanPhams = new HashSet(0);

    public LoaiSanPham() {
    }

	
    public LoaiSanPham(String tenLoaiSp) {
        this.tenLoaiSp = tenLoaiSp;
    }
    public LoaiSanPham(String tenLoaiSp, Set sanPhams) {
       this.tenLoaiSp = tenLoaiSp;
       this.sanPhams = sanPhams;
    }
   
    public Integer getMaLoaiSp() {
        return this.maLoaiSp;
    }
    
    public void setMaLoaiSp(Integer maLoaiSp) {
        this.maLoaiSp = maLoaiSp;
    }
    public String getTenLoaiSp() {
        return this.tenLoaiSp;
    }
    
    public void setTenLoaiSp(String tenLoaiSp) {
        this.tenLoaiSp = tenLoaiSp;
    }
    public Set getSanPhams() {
        return this.sanPhams;
    }
    
    public void setSanPhams(Set sanPhams) {
        this.sanPhams = sanPhams;
    }




}


