package cellphoneshop.model;

// Generated Dec 10, 2013 11:05:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Loaibanphim generated by hbm2java
 */
public class Loaibanphim implements java.io.Serializable {

	private Short maLoaiBanPhim;
	private String tenLoaiBanPhim;
	private Set thongsodtdds = new HashSet(0);
	private Set thongsosmartphones = new HashSet(0);

	public Loaibanphim() {
	}
	
	public Loaibanphim(String tenLoaiBanPhim) {
		this.tenLoaiBanPhim = tenLoaiBanPhim;
	}

	public Loaibanphim(String tenLoaiBanPhim, Set thongsodtdds,
			Set thongsosmartphones) {
		this.tenLoaiBanPhim = tenLoaiBanPhim;
		this.thongsodtdds = thongsodtdds;
		this.thongsosmartphones = thongsosmartphones;
	}

	public Short getMaLoaiBanPhim() {
		return this.maLoaiBanPhim;
	}

	public void setMaLoaiBanPhim(Short maLoaiBanPhim) {
		this.maLoaiBanPhim = maLoaiBanPhim;
	}

	public String getTenLoaiBanPhim() {
		return this.tenLoaiBanPhim;
	}

	public void setTenLoaiBanPhim(String tenLoaiBanPhim) {
		this.tenLoaiBanPhim = tenLoaiBanPhim;
	}

	public Set getThongsodtdds() {
		return this.thongsodtdds;
	}

	public void setThongsodtdds(Set thongsodtdds) {
		this.thongsodtdds = thongsodtdds;
	}

	public Set getThongsosmartphones() {
		return this.thongsosmartphones;
	}

	public void setThongsosmartphones(Set thongsosmartphones) {
		this.thongsosmartphones = thongsosmartphones;
	}

}
