package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Loainguoidung generated by hbm2java
 */
public class Loainguoidung implements java.io.Serializable {

	private Short maLoaiNd;
	private String tenLoaiNd;
	private Set nguoidungs = new HashSet(0);

	public Loainguoidung() {
	}

	public Loainguoidung(String tenLoaiNd) {
		this.tenLoaiNd = tenLoaiNd;
	}

	public Loainguoidung(String tenLoaiNd, Set nguoidungs) {
		this.tenLoaiNd = tenLoaiNd;
		this.nguoidungs = nguoidungs;
	}

	public Short getMaLoaiNd() {
		return this.maLoaiNd;
	}

	public void setMaLoaiNd(Short maLoaiNd) {
		this.maLoaiNd = maLoaiNd;
	}

	public String getTenLoaiNd() {
		return this.tenLoaiNd;
	}

	public void setTenLoaiNd(String tenLoaiNd) {
		this.tenLoaiNd = tenLoaiNd;
	}

	public Set getNguoidungs() {
		return this.nguoidungs;
	}

	public void setNguoidungs(Set nguoidungs) {
		this.nguoidungs = nguoidungs;
	}

}
