package cellphoneshop.model;
// Generated Jan 10, 2010 8:13:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * NguoiNhan generated by hbm2java
 */
public class NguoiNhan  implements java.io.Serializable {


     private int maNguoiNhan;
     private NguoiDung nguoiDung;
     private String hoTen;
     private String soDienThoai;
     private String diaChi;
     private Set donHangs = new HashSet(0);

    public NguoiNhan() {
    }

	
    public NguoiNhan(int maNguoiNhan, NguoiDung nguoiDung, String diaChi) {
        this.maNguoiNhan = maNguoiNhan;
        this.nguoiDung = nguoiDung;
        this.diaChi = diaChi;
    }
    public NguoiNhan(int maNguoiNhan, NguoiDung nguoiDung, String hoTen, String soDienThoai, String diaChi, Set donHangs) {
       this.maNguoiNhan = maNguoiNhan;
       this.nguoiDung = nguoiDung;
       this.hoTen = hoTen;
       this.soDienThoai = soDienThoai;
       this.diaChi = diaChi;
       this.donHangs = donHangs;
    }
   
    public int getMaNguoiNhan() {
        return this.maNguoiNhan;
    }
    
    public void setMaNguoiNhan(int maNguoiNhan) {
        this.maNguoiNhan = maNguoiNhan;
    }
    public NguoiDung getNguoiDung() {
        return this.nguoiDung;
    }
    
    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Set getDonHangs() {
        return this.donHangs;
    }
    
    public void setDonHangs(Set donHangs) {
        this.donHangs = donHangs;
    }




}


