package cellphoneshop.model;
// Generated Dec 21, 2013 12:56:07 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NguoiDung generated by hbm2java
 */
public class NguoiDung  implements java.io.Serializable {


     private Integer maNd;
     private LoaiNguoiDung loaiNguoiDung;
     private String ho;
     private String ten;
     private String email;
     private String matKhau;
     private Integer gioiTinh;
     private Date ngaySinh;
     private String hinhDaiDien;
     private String soDienThoai;
     private String diaChi;
     private Boolean nhanTinQuaEmail;
     private Boolean enable;
     private Set vaiTros = new HashSet(0);
     private Set danhGias = new HashSet(0);
     private Set danhSachMongMuons = new HashSet(0);
     private Set binhLuans = new HashSet(0);
     private Set donHangs = new HashSet(0);
     private Set nguoiNhans = new HashSet(0);

    public NguoiDung() {
    }

	
    public NguoiDung(String ho, String ten, String email, String matKhau, Date ngaySinh) {
        this.ho = ho;
        this.ten = ten;
        this.email = email;
        this.matKhau = matKhau;
        this.ngaySinh = ngaySinh;
    }
    public NguoiDung(LoaiNguoiDung loaiNguoiDung, String ho, String ten, String email, String matKhau, Integer gioiTinh, Date ngaySinh, String hinhDaiDien, String soDienThoai, String diaChi, Boolean nhanTinQuaEmail, Boolean enable, Set vaiTros, Set danhGias, Set danhSachMongMuons, Set binhLuans, Set donHangs, Set nguoiNhans) {
       this.loaiNguoiDung = loaiNguoiDung;
       this.ho = ho;
       this.ten = ten;
       this.email = email;
       this.matKhau = matKhau;
       this.gioiTinh = gioiTinh;
       this.ngaySinh = ngaySinh;
       this.hinhDaiDien = hinhDaiDien;
       this.soDienThoai = soDienThoai;
       this.diaChi = diaChi;
       this.nhanTinQuaEmail = nhanTinQuaEmail;
       this.enable = enable;
       this.vaiTros = vaiTros;
       this.danhGias = danhGias;
       this.danhSachMongMuons = danhSachMongMuons;
       this.binhLuans = binhLuans;
       this.donHangs = donHangs;
       this.nguoiNhans = nguoiNhans;
    }
   
    public Integer getMaNd() {
        return this.maNd;
    }
    
    public void setMaNd(Integer maNd) {
        this.maNd = maNd;
    }
    public LoaiNguoiDung getLoaiNguoiDung() {
        return this.loaiNguoiDung;
    }
    
    public void setLoaiNguoiDung(LoaiNguoiDung loaiNguoiDung) {
        this.loaiNguoiDung = loaiNguoiDung;
    }
    public String getHo() {
        return this.ho;
    }
    
    public void setHo(String ho) {
        this.ho = ho;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public Integer getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(Integer gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public String getHinhDaiDien() {
        return this.hinhDaiDien;
    }
    
    public void setHinhDaiDien(String hinhDaiDien) {
        this.hinhDaiDien = hinhDaiDien;
    }
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Boolean getNhanTinQuaEmail() {
        return this.nhanTinQuaEmail;
    }
    
    public void setNhanTinQuaEmail(Boolean nhanTinQuaEmail) {
        this.nhanTinQuaEmail = nhanTinQuaEmail;
    }
    public Boolean getEnable() {
        return this.enable;
    }
    
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }
    public Set getVaiTros() {
        return this.vaiTros;
    }
    
    public void setVaiTros(Set vaiTros) {
        this.vaiTros = vaiTros;
    }
    public Set getDanhGias() {
        return this.danhGias;
    }
    
    public void setDanhGias(Set danhGias) {
        this.danhGias = danhGias;
    }
    public Set getDanhSachMongMuons() {
        return this.danhSachMongMuons;
    }
    
    public void setDanhSachMongMuons(Set danhSachMongMuons) {
        this.danhSachMongMuons = danhSachMongMuons;
    }
    public Set getBinhLuans() {
        return this.binhLuans;
    }
    
    public void setBinhLuans(Set binhLuans) {
        this.binhLuans = binhLuans;
    }
    public Set getDonHangs() {
        return this.donHangs;
    }
    
    public void setDonHangs(Set donHangs) {
        this.donHangs = donHangs;
    }
    public Set getNguoiNhans() {
        return this.nguoiNhans;
    }
    
    public void setNguoiNhans(Set nguoiNhans) {
        this.nguoiNhans = nguoiNhans;
    }




}


