package cellphoneshop.model;

// Generated Dec 10, 2013 11:05:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nguoidung generated by hbm2java
 */
public class Nguoidung implements java.io.Serializable {

	private Integer maNd;
	private Loainguoidung loainguoidung;
	private String ho;
	private String ten;
	private String tenDangNhap;
	private String email;
	private String matKhau;
	private Short gioiTinh;
	private Date ngaySinh;
	private String hinhDaiDien;
	private String soDienThoai;
	private String diaChi;
	private Boolean nhanTinQuaEmail;
	private Set vaitros = new HashSet(0);
	private Set danhgias = new HashSet(0);
	private Set danhsachmongmuons = new HashSet(0);
	private Set binhluans = new HashSet(0);
	private Set donhangs = new HashSet(0);

	public Nguoidung() {
	}
	
	public Nguoidung(String email, String matKhau) {
		this.email = email;
		this.matKhau = matKhau;
	}

	public Nguoidung(String ho, String ten, String email, String matKhau,
			Date ngaySinh) {
		this.ho = ho;
		this.ten = ten;
		this.email = email;
		this.matKhau = matKhau;
		this.ngaySinh = ngaySinh;
	}

	public Nguoidung(Loainguoidung loainguoidung, String ho, String ten,
			String tenDangNhap, String email, String matKhau, Short gioiTinh,
			Date ngaySinh, String hinhDaiDien, String soDienThoai,
			String diaChi, Boolean nhanTinQuaEmail, Set vaitros, Set danhgias,
			Set danhsachmongmuons, Set binhluans, Set donhangs) {
		this.loainguoidung = loainguoidung;
		this.ho = ho;
		this.ten = ten;
		this.tenDangNhap = tenDangNhap;
		this.email = email;
		this.matKhau = matKhau;
		this.gioiTinh = gioiTinh;
		this.ngaySinh = ngaySinh;
		this.hinhDaiDien = hinhDaiDien;
		this.soDienThoai = soDienThoai;
		this.diaChi = diaChi;
		this.nhanTinQuaEmail = nhanTinQuaEmail;
		this.vaitros = vaitros;
		this.danhgias = danhgias;
		this.danhsachmongmuons = danhsachmongmuons;
		this.binhluans = binhluans;
		this.donhangs = donhangs;
	}

	public Integer getMaNd() {
		return this.maNd;
	}

	public void setMaNd(Integer maNd) {
		this.maNd = maNd;
	}

	public Loainguoidung getLoainguoidung() {
		return this.loainguoidung;
	}

	public void setLoainguoidung(Loainguoidung loainguoidung) {
		this.loainguoidung = loainguoidung;
	}

	public String getHo() {
		return this.ho;
	}

	public void setHo(String ho) {
		this.ho = ho;
	}

	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	public Short getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Short gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getHinhDaiDien() {
		return this.hinhDaiDien;
	}

	public void setHinhDaiDien(String hinhDaiDien) {
		this.hinhDaiDien = hinhDaiDien;
	}

	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public Boolean getNhanTinQuaEmail() {
		return this.nhanTinQuaEmail;
	}

	public void setNhanTinQuaEmail(Boolean nhanTinQuaEmail) {
		this.nhanTinQuaEmail = nhanTinQuaEmail;
	}

	public Set getVaitros() {
		return this.vaitros;
	}

	public void setVaitros(Set vaitros) {
		this.vaitros = vaitros;
	}

	public Set getDanhgias() {
		return this.danhgias;
	}

	public void setDanhgias(Set danhgias) {
		this.danhgias = danhgias;
	}

	public Set getDanhsachmongmuons() {
		return this.danhsachmongmuons;
	}

	public void setDanhsachmongmuons(Set danhsachmongmuons) {
		this.danhsachmongmuons = danhsachmongmuons;
	}

	public Set getBinhluans() {
		return this.binhluans;
	}

	public void setBinhluans(Set binhluans) {
		this.binhluans = binhluans;
	}

	public Set getDonhangs() {
		return this.donhangs;
	}

	public void setDonhangs(Set donhangs) {
		this.donhangs = donhangs;
	}

}
