package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Phieugiaohang generated by hbm2java
 */
public class Phieugiaohang implements java.io.Serializable {

	private Long maPhieuGiaoHang;
	private Donhang donhang;
	private Date ngayGiao;

	public Phieugiaohang() {
	}

	public Phieugiaohang(Donhang donhang, Date ngayGiao) {
		this.donhang = donhang;
		this.ngayGiao = ngayGiao;
	}

	public Long getMaPhieuGiaoHang() {
		return this.maPhieuGiaoHang;
	}

	public void setMaPhieuGiaoHang(Long maPhieuGiaoHang) {
		this.maPhieuGiaoHang = maPhieuGiaoHang;
	}

	public Donhang getDonhang() {
		return this.donhang;
	}

	public void setDonhang(Donhang donhang) {
		this.donhang = donhang;
	}

	public Date getNgayGiao() {
		return this.ngayGiao;
	}

	public void setNgayGiao(Date ngayGiao) {
		this.ngayGiao = ngayGiao;
	}

}
