package cellphoneshop.model;
// Generated Jan 10, 2010 7:19:00 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PhieuGiaoHang generated by hbm2java
 */
public class PhieuGiaoHang  implements java.io.Serializable {


     private Integer maPhieuGiaoHang;
     private DonHang donHang;
     private Date ngayGiao;

    public PhieuGiaoHang() {
    }

    public PhieuGiaoHang(DonHang donHang, Date ngayGiao) {
       this.donHang = donHang;
       this.ngayGiao = ngayGiao;
    }
   
    public Integer getMaPhieuGiaoHang() {
        return this.maPhieuGiaoHang;
    }
    
    public void setMaPhieuGiaoHang(Integer maPhieuGiaoHang) {
        this.maPhieuGiaoHang = maPhieuGiaoHang;
    }
    public DonHang getDonHang() {
        return this.donHang;
    }
    
    public void setDonHang(DonHang donHang) {
        this.donHang = donHang;
    }
    public Date getNgayGiao() {
        return this.ngayGiao;
    }
    
    public void setNgayGiao(Date ngayGiao) {
        this.ngayGiao = ngayGiao;
    }




}


