package cellphoneshop.model;
// Generated Jan 10, 2010 7:19:00 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * PtGiaoHang generated by hbm2java
 */
public class PtGiaoHang  implements java.io.Serializable {


     private Integer maPtgiaoHang;
     private String tenPtgiaoHang;
     private Set donHangs = new HashSet(0);

    public PtGiaoHang() {
    }

	
    public PtGiaoHang(String tenPtgiaoHang) {
        this.tenPtgiaoHang = tenPtgiaoHang;
    }
    public PtGiaoHang(String tenPtgiaoHang, Set donHangs) {
       this.tenPtgiaoHang = tenPtgiaoHang;
       this.donHangs = donHangs;
    }
   
    public Integer getMaPtgiaoHang() {
        return this.maPtgiaoHang;
    }
    
    public void setMaPtgiaoHang(Integer maPtgiaoHang) {
        this.maPtgiaoHang = maPtgiaoHang;
    }
    public String getTenPtgiaoHang() {
        return this.tenPtgiaoHang;
    }
    
    public void setTenPtgiaoHang(String tenPtgiaoHang) {
        this.tenPtgiaoHang = tenPtgiaoHang;
    }
    public Set getDonHangs() {
        return this.donHangs;
    }
    
    public void setDonHangs(Set donHangs) {
        this.donHangs = donHangs;
    }




}


