package cellphoneshop.model;

// Generated Dec 10, 2013 11:05:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ptgiaohang generated by hbm2java
 */
public class Ptgiaohang implements java.io.Serializable {

	private Short maPtgiaoHang;
	private String tenPtgiaoHang;
	private Set donhangs = new HashSet(0);

	public Ptgiaohang() {
	}

	public Ptgiaohang(String tenPtgiaoHang) {
		this.tenPtgiaoHang = tenPtgiaoHang;
	}

	public Ptgiaohang(String tenPtgiaoHang, Set donhangs) {
		this.tenPtgiaoHang = tenPtgiaoHang;
		this.donhangs = donhangs;
	}

	public Short getMaPtgiaoHang() {
		return this.maPtgiaoHang;
	}

	public void setMaPtgiaoHang(Short maPtgiaoHang) {
		this.maPtgiaoHang = maPtgiaoHang;
	}

	public String getTenPtgiaoHang() {
		return this.tenPtgiaoHang;
	}

	public void setTenPtgiaoHang(String tenPtgiaoHang) {
		this.tenPtgiaoHang = tenPtgiaoHang;
	}

	public Set getDonhangs() {
		return this.donhangs;
	}

	public void setDonhangs(Set donhangs) {
		this.donhangs = donhangs;
	}

}
