package cellphoneshop.model;
// Generated Jan 10, 2010 8:52:59 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * PtThanhToan generated by hbm2java
 */
public class PtThanhToan  implements java.io.Serializable {


     private Integer maPtthanhToan;
     private String tenPtthanhToan;
     private String ghiChu;
     private Set donHangs = new HashSet(0);

    public PtThanhToan() {
    }

	
    public PtThanhToan(String tenPtthanhToan) {
        this.tenPtthanhToan = tenPtthanhToan;
    }
    public PtThanhToan(String tenPtthanhToan, String ghiChu, Set donHangs) {
       this.tenPtthanhToan = tenPtthanhToan;
       this.ghiChu = ghiChu;
       this.donHangs = donHangs;
    }
   
    public Integer getMaPtthanhToan() {
        return this.maPtthanhToan;
    }
    
    public void setMaPtthanhToan(Integer maPtthanhToan) {
        this.maPtthanhToan = maPtthanhToan;
    }
    public String getTenPtthanhToan() {
        return this.tenPtthanhToan;
    }
    
    public void setTenPtthanhToan(String tenPtthanhToan) {
        this.tenPtthanhToan = tenPtthanhToan;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Set getDonHangs() {
        return this.donHangs;
    }
    
    public void setDonHangs(Set donHangs) {
        this.donHangs = donHangs;
    }




}


