package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Thongsoadapter generated by hbm2java
 */
public class Thongsoadapter implements java.io.Serializable {

	private Long maThongSoAdapter;
	private String inputAc;
	private String outputDc;
	private String kieuGiacCam;
	private Set ctsanphams = new HashSet(0);

	public Thongsoadapter() {
	}

	public Thongsoadapter(String inputAc, String outputDc, String kieuGiacCam,
			Set ctsanphams) {
		this.inputAc = inputAc;
		this.outputDc = outputDc;
		this.kieuGiacCam = kieuGiacCam;
		this.ctsanphams = ctsanphams;
	}

	public Long getMaThongSoAdapter() {
		return this.maThongSoAdapter;
	}

	public void setMaThongSoAdapter(Long maThongSoAdapter) {
		this.maThongSoAdapter = maThongSoAdapter;
	}

	public String getInputAc() {
		return this.inputAc;
	}

	public void setInputAc(String inputAc) {
		this.inputAc = inputAc;
	}

	public String getOutputDc() {
		return this.outputDc;
	}

	public void setOutputDc(String outputDc) {
		this.outputDc = outputDc;
	}

	public String getKieuGiacCam() {
		return this.kieuGiacCam;
	}

	public void setKieuGiacCam(String kieuGiacCam) {
		this.kieuGiacCam = kieuGiacCam;
	}

	public Set getCtsanphams() {
		return this.ctsanphams;
	}

	public void setCtsanphams(Set ctsanphams) {
		this.ctsanphams = ctsanphams;
	}

}
