package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Thongsothenho generated by hbm2java
 */
public class Thongsothenho implements java.io.Serializable {

	private Long maThongSoTheNho;
	private Short dungLuong;
	private Float tocDoDoc;
	private Float tocDoGhi;
	private Short class_;
	private String serial;
	private Set ctsanphams = new HashSet(0);

	public Thongsothenho() {
	}

	public Thongsothenho(Short dungLuong, Float tocDoDoc, Float tocDoGhi,
			Short class_, String serial, Set ctsanphams) {
		this.dungLuong = dungLuong;
		this.tocDoDoc = tocDoDoc;
		this.tocDoGhi = tocDoGhi;
		this.class_ = class_;
		this.serial = serial;
		this.ctsanphams = ctsanphams;
	}

	public Long getMaThongSoTheNho() {
		return this.maThongSoTheNho;
	}

	public void setMaThongSoTheNho(Long maThongSoTheNho) {
		this.maThongSoTheNho = maThongSoTheNho;
	}

	public Short getDungLuong() {
		return this.dungLuong;
	}

	public void setDungLuong(Short dungLuong) {
		this.dungLuong = dungLuong;
	}

	public Float getTocDoDoc() {
		return this.tocDoDoc;
	}

	public void setTocDoDoc(Float tocDoDoc) {
		this.tocDoDoc = tocDoDoc;
	}

	public Float getTocDoGhi() {
		return this.tocDoGhi;
	}

	public void setTocDoGhi(Float tocDoGhi) {
		this.tocDoGhi = tocDoGhi;
	}

	public Short getClass_() {
		return this.class_;
	}

	public void setClass_(Short class_) {
		this.class_ = class_;
	}

	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	public Set getCtsanphams() {
		return this.ctsanphams;
	}

	public void setCtsanphams(Set ctsanphams) {
		this.ctsanphams = ctsanphams;
	}

}
