package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Thongsopin generated by hbm2java
 */
public class Thongsopin implements java.io.Serializable {

	private Long maThongSoPin;
	private Float dungLuongPin;
	private Float dienAp;
	private String congNghe;
	private Set ctsanphams = new HashSet(0);

	public Thongsopin() {
	}

	public Thongsopin(Float dungLuongPin, Float dienAp, String congNghe,
			Set ctsanphams) {
		this.dungLuongPin = dungLuongPin;
		this.dienAp = dienAp;
		this.congNghe = congNghe;
		this.ctsanphams = ctsanphams;
	}

	public Long getMaThongSoPin() {
		return this.maThongSoPin;
	}

	public void setMaThongSoPin(Long maThongSoPin) {
		this.maThongSoPin = maThongSoPin;
	}

	public Float getDungLuongPin() {
		return this.dungLuongPin;
	}

	public void setDungLuongPin(Float dungLuongPin) {
		this.dungLuongPin = dungLuongPin;
	}

	public Float getDienAp() {
		return this.dienAp;
	}

	public void setDienAp(Float dienAp) {
		this.dienAp = dienAp;
	}

	public String getCongNghe() {
		return this.congNghe;
	}

	public void setCongNghe(String congNghe) {
		this.congNghe = congNghe;
	}

	public Set getCtsanphams() {
		return this.ctsanphams;
	}

	public void setCtsanphams(Set ctsanphams) {
		this.ctsanphams = ctsanphams;
	}

}
