package cellphoneshop.model;

// Generated Dec 10, 2013 11:05:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * Thongsotainghe generated by hbm2java
 */
public class Thongsotainghe implements java.io.Serializable {

	private Long maThongSoTaiNghe;
	private Ctsanpham ctsanpham;
	private Float kichThuoc;
	private Float congSuat;
	private String tanSo;
	private Short doNhay;
	private Short troKhangDauVao;

	public Thongsotainghe() {
	}

	public Thongsotainghe(Ctsanpham ctsanpham) {
		this.ctsanpham = ctsanpham;
	}

	public Thongsotainghe(Ctsanpham ctsanpham, Float kichThuoc, Float congSuat,
			String tanSo, Short doNhay, Short troKhangDauVao) {
		this.ctsanpham = ctsanpham;
		this.kichThuoc = kichThuoc;
		this.congSuat = congSuat;
		this.tanSo = tanSo;
		this.doNhay = doNhay;
		this.troKhangDauVao = troKhangDauVao;
	}

	public Long getMaThongSoTaiNghe() {
		return this.maThongSoTaiNghe;
	}

	public void setMaThongSoTaiNghe(Long maThongSoTaiNghe) {
		this.maThongSoTaiNghe = maThongSoTaiNghe;
	}

	public Ctsanpham getCtsanpham() {
		return this.ctsanpham;
	}

	public void setCtsanpham(Ctsanpham ctsanpham) {
		this.ctsanpham = ctsanpham;
	}

	public Float getKichThuoc() {
		return this.kichThuoc;
	}

	public void setKichThuoc(Float kichThuoc) {
		this.kichThuoc = kichThuoc;
	}

	public Float getCongSuat() {
		return this.congSuat;
	}

	public void setCongSuat(Float congSuat) {
		this.congSuat = congSuat;
	}

	public String getTanSo() {
		return this.tanSo;
	}

	public void setTanSo(String tanSo) {
		this.tanSo = tanSo;
	}

	public Short getDoNhay() {
		return this.doNhay;
	}

	public void setDoNhay(Short doNhay) {
		this.doNhay = doNhay;
	}

	public Short getTroKhangDauVao() {
		return this.troKhangDauVao;
	}

	public void setTroKhangDauVao(Short troKhangDauVao) {
		this.troKhangDauVao = troKhangDauVao;
	}

}
