package cellphoneshop.model;

// Generated Dec 10, 2013 9:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Thongsotainghe generated by hbm2java
 */
public class Thongsotainghe implements java.io.Serializable {

	private Long maThongSoTaiNghe;
	private Float kichThuoc;
	private Float congSuat;
	private String tanSo;
	private Short doNhay;
	private Short troKhangDauVao;
	private Set ctsanphams = new HashSet(0);

	public Thongsotainghe() {
	}

	public Thongsotainghe(Float kichThuoc, Float congSuat, String tanSo,
			Short doNhay, Short troKhangDauVao, Set ctsanphams) {
		this.kichThuoc = kichThuoc;
		this.congSuat = congSuat;
		this.tanSo = tanSo;
		this.doNhay = doNhay;
		this.troKhangDauVao = troKhangDauVao;
		this.ctsanphams = ctsanphams;
	}

	public Long getMaThongSoTaiNghe() {
		return this.maThongSoTaiNghe;
	}

	public void setMaThongSoTaiNghe(Long maThongSoTaiNghe) {
		this.maThongSoTaiNghe = maThongSoTaiNghe;
	}

	public Float getKichThuoc() {
		return this.kichThuoc;
	}

	public void setKichThuoc(Float kichThuoc) {
		this.kichThuoc = kichThuoc;
	}

	public Float getCongSuat() {
		return this.congSuat;
	}

	public void setCongSuat(Float congSuat) {
		this.congSuat = congSuat;
	}

	public String getTanSo() {
		return this.tanSo;
	}

	public void setTanSo(String tanSo) {
		this.tanSo = tanSo;
	}

	public Short getDoNhay() {
		return this.doNhay;
	}

	public void setDoNhay(Short doNhay) {
		this.doNhay = doNhay;
	}

	public Short getTroKhangDauVao() {
		return this.troKhangDauVao;
	}

	public void setTroKhangDauVao(Short troKhangDauVao) {
		this.troKhangDauVao = troKhangDauVao;
	}

	public Set getCtsanphams() {
		return this.ctsanphams;
	}

	public void setCtsanphams(Set ctsanphams) {
		this.ctsanphams = ctsanphams;
	}

}
