package cellphoneshop.model;

// Generated Dec 10, 2013 11:05:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Trangthaidonhang generated by hbm2java
 */
public class Trangthaidonhang implements java.io.Serializable {

	private Short maTrangThai;
	private String tenTrangThai;
	private Set donhangs = new HashSet(0);

	public Trangthaidonhang() {
	}

	public Trangthaidonhang(String tenTrangThai) {
		this.tenTrangThai = tenTrangThai;
	}

	public Trangthaidonhang(String tenTrangThai, Set donhangs) {
		this.tenTrangThai = tenTrangThai;
		this.donhangs = donhangs;
	}

	public Short getMaTrangThai() {
		return this.maTrangThai;
	}

	public void setMaTrangThai(Short maTrangThai) {
		this.maTrangThai = maTrangThai;
	}

	public String getTenTrangThai() {
		return this.tenTrangThai;
	}

	public void setTenTrangThai(String tenTrangThai) {
		this.tenTrangThai = tenTrangThai;
	}

	public Set getDonhangs() {
		return this.donhangs;
	}

	public void setDonhangs(Set donhangs) {
		this.donhangs = donhangs;
	}

}
