package cellphoneshop.model;
// Generated Dec 20, 2013 12:09:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TrangThaiKhuyenMai generated by hbm2java
 */
public class TrangThaiKhuyenMai  implements java.io.Serializable {


     private Integer maTrangThai;
     private String tenTrangThai;
     private Set khuyenMais = new HashSet(0);

    public TrangThaiKhuyenMai() {
    }

	
    public TrangThaiKhuyenMai(String tenTrangThai) {
        this.tenTrangThai = tenTrangThai;
    }
    public TrangThaiKhuyenMai(String tenTrangThai, Set khuyenMais) {
       this.tenTrangThai = tenTrangThai;
       this.khuyenMais = khuyenMais;
    }
   
    public Integer getMaTrangThai() {
        return this.maTrangThai;
    }
    
    public void setMaTrangThai(Integer maTrangThai) {
        this.maTrangThai = maTrangThai;
    }
    public String getTenTrangThai() {
        return this.tenTrangThai;
    }
    
    public void setTenTrangThai(String tenTrangThai) {
        this.tenTrangThai = tenTrangThai;
    }
    public Set getKhuyenMais() {
        return this.khuyenMais;
    }
    
    public void setKhuyenMais(Set khuyenMais) {
        this.khuyenMais = khuyenMais;
    }




}


