package cellphoneshop.viewmodel;

import java.util.Date;

// Generated Dec 20, 2013 12:09:05 PM by Hibernate Tools 3.2.1.GA
/**
 * KhuyenMai generated by hbm2java
 */
public class UpdateKhuyenMai  implements java.io.Serializable {
     private Integer maKm;
     private String tieuDe;
     private String moTa;
	private Float phanTramGiamGia;
     private Date ngayKetThuc;
     private Date ngayBatDau;
     private String quaTang;
     private String hinhAnh;
	public Integer getMaKm() {
		return maKm;
	}
	public void setMaKm(Integer maKm) {
		this.maKm = maKm;
	}
	public String getTieuDe() {
		return tieuDe;
	}
	public void setTieuDe(String tieuDe) {
		this.tieuDe = tieuDe;
	}
	public String getMoTa() {
		return moTa;
	}
	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}
	public Float getPhanTramGiamGia() {
		return phanTramGiamGia;
	}
	public void setPhanTramGiamGia(Float phanTramGiamGia) {
		this.phanTramGiamGia = phanTramGiamGia;
	}
	public Date getNgayKetThuc() {
		return ngayKetThuc;
	}
	public void setNgayKetThuc(Date ngayKetThuc) {
		this.ngayKetThuc = ngayKetThuc;
	}
	public Date getNgayBatDau() {
		return ngayBatDau;
	}
	public void setNgayBatDau(Date ngayBatDau) {
		this.ngayBatDau = ngayBatDau;
	}
	public String getQuaTang() {
		return quaTang;
	}
	public void setQuaTang(String quaTang) {
		this.quaTang = quaTang;
	}
	public String getHinhAnh() {
		return hinhAnh;
	}
	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}   
}


